CREATE TABLE `Employee` (
  `EmployeeID` CHAR(3) NOT NULL,
  `Name` VARCHAR(20) DEFAULT NULL,
  `EnglishName` VARCHAR(20) DEFAULT NULL,
  `Title` VARCHAR(10) DEFAULT NULL,
  `Gender` CHAR(2) DEFAULT NULL,
  `BirthDate` DATE DEFAULT NULL,
  `HireDate` DATE DEFAULT NULL,
  `Address` VARCHAR(50) DEFAULT NULL,
  `City` VARCHAR(20) DEFAULT NULL,
  `Region` VARCHAR(20) DEFAULT NULL,
  `HomePhone` VARCHAR(20) DEFAULT NULL,
  `ManagerID` CHAR(3) DEFAULT NULL,
  `DepartmentID` CHAR(2) DEFAULT NULL,
  PRIMARY KEY (`EmployeeID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;